### ISSUE TITLE
URDF rules that can be load

### ISSUE THREAD

**Issue by Biruberuvinto** [chvmp/champ_setup_assistant#1]
Hello.
Thank you for making a great tool.

Is there a rule in URDF that this tool can load?
The sample URDF, ANYMAL, loaded successfully.
However, I was not able to read the URDF of a completely different 3-axis robot arm.
The error message: "poll failed with error Interrupted system call" is displayed and the process ends.

Thank you.

**Comment by grassjelly** [comment]
Hi,

This setup assistant is mainly for quadrupedal robots, for this project to be exact - https://github.com/chvmp/champ. 

Unless you meant, you’re loading a quadrupedal robot’s URDF with a robotic arm?

**Comment by Biruberuvinto** [comment]
Thank you for your prompt reply.

I know the purpose of the tool is champ.

I interested if a simple robot arm could be used instead of the URDF of a quadrupedal robot equipped with a robot arm.
Because I tried to set up a quadrupedal robot with other joints with this tool.

**Comment by Biruberuvinto** [comment]
@grassjelly 
When I referred to the source file (urdf_parser.py), it said that it was adding to the new list when the number of end links was four.
Lines 227 to 234.

This means that a URDF that doesn't have 4 endlinks will not be added to the list and will fail?

**Comment by grassjelly** [comment]
The function acts as a filter by removing a potential manipulator in the urdf file. This works by checking the number of actuators in each chain and counting how many times that number occured. If that number has occurred 4 times(4 legs) most likely the end link belongs to a leg, otherwise it will omit.

**Comment by Biruberuvinto** [comment]
It was helpful. Thank you very much.

Incidentally, I tried to generate it with the URDF file of "https://github.com/ReactRobotics/DogBotV4/tree/master/ROS".
Then the following notice was displayed on the terminal.

[WARN] [1596091560.599070]: base_joint's xyz are not defined. Setting these values ​​to zero
[WARN] [1596091560.599573]: base_joint's rpy are not defined. Setting these values ​​to zero
[WARN] [1596091560.600328]: base_joint's xyz are not defined. Setting these values ​​to zero
[WARN] [1596091560.600689]: base_joint's rpy are not defined. Setting these values ​​to zero
[WARN] [1596091560.601352]: base_joint's xyz are not defined. Setting these values ​​to zero
[WARN] [1596091560.601682]: base_joint's rpy are not defined. Setting these values ​​to zero
[WARN] [1596091560.602307]: base_joint's xyz are not defined. Setting these values ​​to zero
[WARN] [1596091560.602631]: base_joint's rpy are not defined.Setting these values ​​to zero

When I try the generated file with the command: "$ roslaunch bringup.launch rviz:=true", it looks like the picture.
Do you know how to fix the error?
![image](https://user-images.githubusercontent.com/51066397/88890850-30d17600-d27d-11ea-823b-38f0e9c46fe4.png)

**Comment by grassjelly** [comment]
Can you please post this as a separate thread in the champ repository instead as it's a different issue. Thanks! Closing this for now.
