### ISSUE TITLE
Robot works fine in RVIZ but not loading in Gazebo

### ISSUE THREAD

**Issue by ShubhamNandi** [chvmp/champ_setup_assistant#10]
I created the urdf model using the [Fusion2URDF](https://github.com/syuntoku14/fusion2urdf) plugin in **Fusion360**.
I am also providing the [repo link](https://github.com/ShubhamNandi/dot) for the respective pkg 
Below are the imgs from **Gazebo** and **RVIZ**

![Screenshot 2021-09-17 at 12 29 24 AM](https://user-images.githubusercontent.com/28607689/133676498-3f8ad9e9-51f3-4249-8d72-f8058ffc8e1a.png)
![Screenshot 2021-09-17 at 12 29 57 AM](https://user-images.githubusercontent.com/28607689/133676529-8ac6a8e8-045c-47db-9ff3-2d67db9ddc6f.png)
![Screenshot 2021-09-17 at 12 28 59 AM](https://user-images.githubusercontent.com/28607689/133676540-5003ddc7-a629-4370-b998-c7aff3e419f0.png)

**Comment by grassjelly** [comment]
You'll need to modify the URDF generated from the plugin and comply with these assumptions: https://github.com/chvmp/champ_setup_assistant#31-using-a-urdf-file. The current IK engine only works if the axes of rotation for the hip, upper leg, and knee are the same as the one mentioned on the document.

**Comment by ShubhamNandi** [comment]
Yes, the axis of rotation is the same as mentioned in the [docs](https://github.com/chvmp/champ_setup_assistant#31-using-a-urdf-file)
So, I change the PID values, in the config pkg that's created; doing so my robot is launched properly but it's bouncing all over the place, possibly due to the untuned PID values.
So basically in RVIZ its works great but in the gazebo, it's not as expected!

**Comment by grassjelly** [comment]
thanks! Please close the issue if the reported issue was resolved. Thanks!

**Comment by ShubhamNandi** [comment]
No, it's not yet solved it just bouncing around in my gazebo how do I fix that? I'm not able to load the model in Gazebo as required

**Comment by grassjelly** [comment]
Can you open a new issue? Please close If you managed to solve the issue (loading the model in gazebo)

**Comment by ShubhamNandi** [comment]
ok sure
