### ISSUE TITLE
Can‘t visualize and control

### ISSUE THREAD

**Issue by skywoodsz** [chvmp/champ_setup_assistant#11]
Hi， 
    I followed guideline to generate the configuration file with ANYmal,  but I can't visualize it in the rviz.
The result is like this：
![1](https://user-images.githubusercontent.com/36660984/139575524-86d1dd6e-a03b-4724-ba66-7f39fe7d027f.png)

And also I can't control it in the gazebo.
![屏幕截图 2021-10-31 17:08:36](https://user-images.githubusercontent.com/36660984/139575663-4e82ac30-f35a-44e5-ae9e-994d13fdd5b5.png)

How can I fix this error? Thanks!

**Comment by grassjelly** [comment]
Have you tried using the default config package for Anymal https://github.com/chvmp/robots/tree/master/configs/anymal_b_config?

**Comment by skywoodsz** [comment]
> Have you tried using the default config package for Anymal https://github.com/chvmp/robots/tree/master/configs/anymal_b_config?

yeah, I tried the default config package. However,  when I run the gazebo config,  the above result will happen. It seems like it was not successfully added to the controller. My sys is ubuntu1604.

**Comment by skywoodsz** [comment]
> Have you tried using the default config package for Anymal https://github.com/chvmp/robots/tree/master/configs/anymal_b_config?

Thanks, sir. I have solved this problem. The problem is caused by a mismatch between the urdf file and the controller, and finally  I unsuccessfully load the controller. I used the anymal_b urdf file form ANYbotics. It seems you change this file?
