### ISSUE TITLE
PluginlibFactory: The plugin for class 'champ/RobotState' failed to load

### ISSUE THREAD

**Issue by elpimous** [chvmp/champ_setup_assistant#16]
hello, on ros NOETIC, i'm facing this issue :+1: 
`[ERROR] [1654418331.360235595]: PluginlibFactory: The plugin for class 'champ/RobotState' failed to load.  Error: According to the loaded plugin descriptions the class champ/RobotState with base class type rviz::Display does not exist. Declared types are  rviz/AccelStamped rviz/Axes rviz/Camera rviz/DepthCloud rviz/Effort rviz/FluidPressure rviz/Grid rviz/GridCells rviz/Illuminance rviz/Image rviz/InteractiveMarkers rviz/LaserScan rviz/Map rviz/Marker rviz/MarkerArray rviz/Odometry rviz/Path rviz/PointCloud rviz/PointCloud2 rviz/PointStamped rviz/Polygon rviz/Pose rviz/PoseArray rviz/PoseWithCovariance rviz/Range rviz/RelativeHumidity rviz/RobotModel rviz/TF rviz/Temperature rviz/TwistStamped rviz/WrenchStamped rviz_plugin_tutorials/Imu
`
Any idea ?

**Comment by elpimous** [comment]
Solved, using noetic branch, and a catkin_make clean.

**Comment by Masa0u0** [comment]
I faced exactly the same problem, but `$ sudo reboot` solved it.
