### ISSUE TITLE
How to generate a correct config file

### ISSUE THREAD

**Issue by Biruberuvinto** [chvmp/champ_setup_assistant#2]
https://github.com/chvmp/champ_setup_assistant/issues/1#issuecomment-666169620
I'm so sorry I didn't know the issue etiquette.

I tried to generate it with the URDF file of "https://github.com/ReactRobotics/DogBotV4/tree/master/ROS".
Then the following notice was displayed on the terminal.

[WARN] [1596091560.599070]: base_joint's xyz are not defined. Setting these values ​​to zero
[WARN] [1596091560.599573]: base_joint's rpy are not defined. Setting these values ​​to zero
[WARN] [1596091560.600328]: base_joint's xyz are not defined. Setting these values ​​to zero
[WARN] [1596091560.600689]: base_joint's rpy are not defined. Setting these values ​​to zero
[WARN] [1596091560.601352]: base_joint's xyz are not defined. Setting these values ​​to zero
[WARN] [1596091560.601682]: base_joint's rpy are not defined. Setting these values ​​to zero
[WARN] [1596091560.602307]: base_joint's xyz are not defined. Setting these values ​​to zero
[WARN] [1596091560.602631]: base_joint's rpy are not defined.Setting these values ​​to zero

When I try the generated file with the command: "$ roslaunch bringup.launch rviz:=true", it looks like the picture.
Do you know how to fix the error?
![image](https://user-images.githubusercontent.com/51066397/88891641-7b9fbd80-d27e-11ea-980e-7d871f18e2ec.png)

**Comment by grassjelly** [comment]
Hi,

I took a quick glance on DogBot's URDF and it seems that  there must be some modifications done on the URDF to make it work with CHAMP's stack. Currently  CHAMP doesnt support rotation on joints and the following guidelines must be followed:

a. Hip joint's rotation of axis must be in X axis
b. Upper Leg joint's rotation of axis must be in Y axis
c. Lower Leg joint's rotation of axis must be in Y axis

You can check out the preconfigured robots as a reference: https://github.com/chvmp/robots/

all the preconfigured config packages are in the config folder and URDF packages can be found on install_description script.

My apologies for the confusion, I'm currently working on hardware documentation and integration guidelines to help users configure their own robots.

Hope this helps.

**Comment by Biruberuvinto** [comment]
Thank you for the detailed explanation.
I found that the joint had to be aligned with the correct axis.

I'm looking forward to being able to handle the self made robot with this tool.
We are waiting for the completion of the guidelines.

**Comment by grassjelly** [comment]
Are you planning to build this platform? I can probably help to convert the urdf

**Comment by Biruberuvinto** [comment]
I'm very happy with the proposal!
Should I modify the URDF file or the setup assistant for a successful conversion?

For now, I searching that axis able to modify on source code("urdf_parser.py", "leg_configurator*.py" , and "config_predict.py").

**Comment by grassjelly** [comment]
You should modify the URDF. You can refer to the listed robots I mentioned earlier to have an Idea how the orientation of axes should be like.
