### ISSUE TITLE
[help wanted] config file isn't being generated properly

### ISSUE THREAD

**Issue by abdu7rahman** [chvmp/champ_setup_assistant#20]
![Screenshot from 2023-03-25 07-58-19](https://user-images.githubusercontent.com/78921503/227682100-1f42116c-3f3d-4832-ab46-e9449f003eaa.png)

these are my gait configurations
knee_orientation : ">>"
pantograph_leg : false
odom_scaler: 1.0
max_linear_velocity_x : 0.5
max_linear_velocity_y : 0.25
max_angular_velocity_z : 1.0
com_x_translation : 0.0
swing_height : 0.012
stance_depth : 0.0
stance_duration : 0.25
nominal_height : 0.2

i need some urgent help on this
![Screenshot from 2023-03-25 08-02-46](https://user-images.githubusercontent.com/78921503/227682242-80270fbd-7385-478d-9341-ed8f925fdc70.png)

im using ubuntu 20.04,  ros noetic, i made the necessary changes for the setup_assistant to work in noetic

**Comment by abdu7rahman** [comment]
i have calculated the gait parameter values and changed a few values
Robot walking height: 0.15
Leg Stance Height: 0.015
Leg Swing height: 0.05
the issue still exists

**Comment by jdambrosio21** [comment]
What changes did you make to get the setup assistant running in noetic on 20.04? im trying to do the same thing

**Comment by abdu7rahman** [comment]
> What changes did you make to get the setup assistant running in noetic on 20.04? im trying to do the same thing

i actually remade the urdf and made sure i gave the correct axes to each joint and also gave axes for the foot

**Comment by jdambrosio21** [comment]
> > What changes did you make to get the setup assistant running in noetic on 20.04? im trying to do the same thing
> 
> i actually remade the urdf and made sure i gave the correct axes to each joint and also gave axes for the foot

Is this for a custom robot?

**Comment by abdu7rahman** [comment]
> joint

yes

**Comment by abdu7rahman** [comment]
> > > What changes did you make to get the setup assistant running in noetic on 20.04? im trying to do the same thing
> 
> > 
> 
> > i actually remade the urdf and made sure i gave the correct axes to each joint and also gave axes for the foot
> 
> 
> 
> Is this for a custom robot?

yes
