### ISSUE TITLE
urdf joint rule

### ISSUE THREAD

**Issue by treetwo77** [chvmp/champ_setup_assistant#24]
![Screenshot from 2023-09-22 17-39-26](https://github.com/chvmp/champ_setup_assistant/assets/113955421/ca058b8b-052c-4250-ab04-8f7caa80d31f)
![Screenshot from 2023-09-22 17-38-45](https://github.com/chvmp/champ_setup_assistant/assets/113955421/81edcb3c-be7b-4d10-8e2a-04ce3a1ad64a)
Which of the two pictures in the urdf household is it correspond to? If both are not applicable, can I force it to be vertical beyond the limit?

**Comment by grassjelly** [comment]
should be the top photo but with the lower leg straight then define the translation to +x axis. there’s no joint limits at the moment so you’d have to be cautious on that
