### ISSUE TITLE
Not able to start champ_setup_assistant on ROS Noetic.

### ISSUE THREAD

**Issue by alphabeta97** [chvmp/champ_setup_assistant#4]
Hello,
I'm trying to run champ_setup_assistant on Noetic but not able to get it started. Bellow is the file with my errors.
[champ_error.txt](https://github.com/chvmp/champ_setup_assistant/files/6298220/champ_error.txt)
Thank You

**Comment by grassjelly** [comment]
hey @alphabeta97 . Did you manage to resolve this issue?

**Comment by alphabeta97** [comment]
> hey @alphabeta97 . Did you manage to resolve this issue?

No

**Comment by abdul-mannan-khan** [comment]
I got the solution from [here](https://answers.ros.org/question/228268/rviz-attributeerror-module-object-has-no-attribute-visualizationframe/). Thanks to @Aradra. He/She mentioned that 

**"In ros noetic import rviz has to be renamed to from rviz import bindings as rviz"** 

So, just open `rviz_widget.py`, got to line line number 35 and change `import rviz` to `from rviz import bindings as rviz`. 

That's it.
