### ISSUE TITLE
Setup Window

### ISSUE THREAD

**Issue by alphabeta97** [chvmp/champ_setup_assistant#6]
I'm running champ_setup_assistant on Ros Melodic on Hyper-V on Windows 10.
Can someone pls. tell me why am I not able to see complete window of setup assistant.
![csa](https://user-images.githubusercontent.com/64826804/115105614-b61cc800-9f7d-11eb-9b42-b8c10f6ad6a5.png)

**Comment by grassjelly** [comment]
I think your window size is too small? Are you able to change your screen resolution?

**Comment by alphabeta97** [comment]
I changed it from 400 x 400 (default on Hyper-V) something similar to 1366 x 768 which is the actual resolution on my laptop.

**Comment by alphabeta97** [comment]
Proble solved by changing the resolution to 1920x1080.
